INSERT INTO USERS (COUNTRY_ID,NAME,ID) VALUES ('HON','HAN',9);

UPDATE USERS SET ID = 1, COUNTRY = 'HON';

SELECT COUNTRY, Nombre from USERS WHERE COUNTRY_ID IN (SELECT ID FROM COUNTRY WHERE CITY = 'SPS') GROUP BY COUNTRY ORDER BY COUNTRY,Nombre;

INSERT INTO USERS (COUNTRY_ID,NAME,ID) VALUES ('HON','HAN',9);

UPDATE USERS SET ID = 1, COUNTRY = 'HON';

DELETE FROM USERS;